spring:
  application:
    name: analytics

#choose random port
server:
  port: 8080

#this application only registers
eureka:
  client:
    serviceUrl:
            defaultZone: http://172.18.0.254:8761/eureka/
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int(0,99)}

